#https://github.com/sasstools/sass-lint/blob/master/docs/rules/nesting-depth.md

options:
  formatter: stylish

rules:
  property-sort-order: 0
  quotes:
    - 0
  no-vendor-prefixes:
    - 0
  no-ids:
    - 0
  no-transition-all:
    - 0
  empty-line-between-blocks:
    - 0
  extends-before-declarations:
    - 0
  placeholder-in-extend:
    - 0
  extends-before-mixins:
    - 0
  force-pseudo-nesting:
    - 0
  no-important:
    - 0
  mixins-before-declarations:
    - 0
  nesting-depth:
    - 1
    - max-depth: 5
  leading-zero:
    - 0
  no-qualifying-elements:
    - 0
  force-attribute-nesting:
    - 0
  no-color-literals:
    - 0
  class-name-format:
    - 0
  no-mergeable-selectors:
    - 0
  variable-name-format:
    - 0
